---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1pqwf58gml4fvmu4tpywx79pzcfzn9e26uqkkxgkmgxd0kavlrpnsnrxzyr"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1pqwf58gml4fvmu4tpywx79pzcfzn9e26uqkkxgkmgxd0kavlrpnsnrxzyr"
stores:
  yaml:
    indent: 2
