# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Ng2yH3DhVk21tvv2boslqi6FF2X3ev7HA8q10dPQoso=,iv:tu/PJZOLy0E9feXqB5MZm9np4PrWFAzTL/Zcmw2I2J4=,tag:11tW2LYigwD7jETV4GV1nQ==,type:str]
sops:
  age:
    - recipient: age1pqwf58gml4fvmu4tpywx79pzcfzn9e26uqkkxgkmgxd0kavlrpnsnrxzyr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MWsrWXZIQUFRTkJrb3BP
        cXgwS1poak85T29EQy8xVHBEZlJBeUtORnlRCjJDMURLaVRkaVV6eVVRT001dXRZ
        ZnZ6TzBXbmtLSUtYS29hZU5Wb3V2ME0KLS0tIHpQenhDZGJwMU00N3gvNjFiOW55
        bWROamRhc3NaT1JpdVhqWWZQeVhVeUEK008X9Ahe+7q1q8XwJ9tg9Mcs/vG8YcGk
        qGxREQm4eUKdw7QW8/A60cGSx6MrRkLifx7eqhdW+IqJWBVPzpJHUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T22:09:47Z"
  mac: ENC[AES256_GCM,data:OaQQXTGNtEnn2PNCEcaJYImFDeP2PRTnfu1pWBZP4n7OVjqx+8fYCrOvBdSZzx1mNO3FzgnnxgjkTmg1SkipHkd2bCBuwDLobqpv/21Q30gC15HyTS8P1gdvbpT+mSBlep6rLLRL1JG+eA8tnghk8CYrIk7/3DgqD50EJdl2UzE=,iv:WJK9sRiwPKrLWBtf6HLWP6NUMRZnHhBhgzVJh4xrnDE=,tag:jqbjNwZJT7a3m40/EYBkzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
