apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Maj141hueVpIG0zCS7Q=,iv:l5uamY4cz6hVdUOFGc+elYfsg/FAeJ1YBiqWRmQkUs4=,tag:z7e/KXvj3/Hgc/u4g+XqXw==,type:str]
sops:
  age:
    - recipient: age1pqwf58gml4fvmu4tpywx79pzcfzn9e26uqkkxgkmgxd0kavlrpnsnrxzyr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OGtzUXFQZ3ZxOVVqM0VJ
        TFQzWU9odTY3cmlORUpwOTlTYU53T00vaWw0CjhVVXBJdG9XSUJMR0hlREtKT3FP
        UGd2QlZRanREbzE4TUtXcSt0VGZBRzgKLS0tIFVkY09uR2ZDT01VMFF6cU1mSnRX
        ZTFIbVFGalB5alhQRkczSm5yTlYxWG8KYICkU2PeQda1T+G86fxpmwysuOzSoh1X
        6Ed1KI/EofMjkIPmRJhmRiTILpD3dVNfrG4c8WHMxuCkM80z3vN8nQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T22:09:47Z"
  mac: ENC[AES256_GCM,data:lE78rKj6F7TXZDYixa/r6f1EfGJkd2y0fo6lv61Ing48wawHGqa+nAYv1/XXxToZ6Jb4FctFNbUttJJ2Ro3q7VopQNMoOe9hNwyNtds0hj5BjwQ913JCmNppwb/d/4/XyjH1p1gxBWljgmGsAB6nLU/1LTPnw9BFXUuzkYqQHD4=,iv:Vy1HX2EOmUavcMbQSbHSfsl1ZV1Kl4L+DA2KlR0HrHc=,tag:8yglpVp9eRDnGLLVUhnRQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
